import sellerImage from "../assets/seller.png";

export const sellers = [
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
  {
    id: 1,
    name: "ملابس الصيرفي",
    image: sellerImage,
    reviewsNum: 121,
    totalProducts: 129,
  },
];
