import { Button, Stack } from "@mui/material";
import React, { useState } from "react";
import CustomizeDelivery from "../../../sections/Dashboard/delivery/CustomizeDelivery";
import CustomizeSection from "./CustomizeSection";
const sellers = [
  {
    id: 0,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 1,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: true,
  },
  {
    id: 2,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: true,
  },
  {
    id: 3,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 4,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 5,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 6,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 7,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: true,
  },
  {
    id: 8,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 9,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 10,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 11,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 12,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 13,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 14,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 15,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 16,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 17,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 18,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 19,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 20,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 21,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 22,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 23,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 24,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 25,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 26,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 27,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 28,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 29,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 30,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 31,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 32,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 33,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 34,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 35,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 36,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 37,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 38,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 39,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 40,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 41,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 42,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 43,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 44,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 45,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 46,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 47,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 48,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 49,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 50,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 51,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 52,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 53,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 54,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 55,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 56,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 57,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 58,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 59,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 60,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 61,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 62,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
  {
    id: 63,
    name: "الصيرفي ستور",
    deliveryName: "شحن چوملا",
    deliveryPrice: 50,
    selected: false,
  },
];
const SellerDeliveryCustomizePage = () => {
  const [showNext, setShowNext] = useState(false);
  return (
    <Stack>
      {showNext && <CustomizeSection title="تخصيص الشحن لبائع" />}
      {!showNext && (
        <CustomizeDelivery title="تخصيص الشحن لبائع" items={sellers} />
      )}
      {!showNext && (
        <Button
          sx={{
            width: "461px",
            height: "92px",
            borderRadius: "15px",
            fontSize: "32px",
            fontWeight: "800",
            lineHeight: "36px",
            "&, &:hover": {
              backgroundColor: "colors.mainGreen",
              color: "colors.wi8",
            },
            mx: "auto",
            my: "100px",
          }}
          onClick={() => {
            setShowNext(true);
            window.scrollTo(0, 0);
          }}
        >
          التالى
        </Button>
      )}
    </Stack>
  );
};

export default SellerDeliveryCustomizePage;
